# Generated by Django 3.1.1 on 2020-10-08 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.IntegerField()),
                ('meds', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('sku_value', models.CharField(max_length=50)),
                ('genericName', models.CharField(max_length=20)),
                ('commonBrand', models.CharField(max_length=20)),
                ('manufacturedDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('use', models.TextField()),
                ('effects', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('religion', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('spouseName', models.CharField(max_length=100)),
                ('spouseOccupation', models.CharField(max_length=100)),
                ('noChildren', models.IntegerField()),
                ('motherName', models.CharField(max_length=100)),
                ('motherOccupation', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('fatherOccupation', models.CharField(max_length=100)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy.person')),
                ('dateRegistered', models.DateField(default=datetime.datetime.now)),
                ('medicine', models.ManyToManyField(to='pharmacy.Medicine')),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('pharmacy.person',),
        ),
    ]
